language: node_js
sudo: false
branches:
  only:
    - master
script:
- node dist/build.js
node_js:
- '4.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
- chmod a+x ./deploy.sh
- ./deploy.sh
